# Generated by Django 3.1.6 on 2021-02-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_text',
            field=models.TextField(null=True),
        ),
    ]
