# Generated by Django 3.1.6 on 2021-02-08 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_posts_post_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='like_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_child', to='post.posts')),
            ],
        ),
    ]
